# Generated by Django 2.2.10 on 2021-02-09 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=50)),
                ('currency_name', models.CharField(max_length=50)),
                ('currency_symbol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ticker', models.CharField(max_length=50)),
                ('average_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_portfolio_tracker_app.Currency')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_from_sold', models.FloatField()),
                ('profit_from_dividends', models.FloatField()),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_portfolio_tracker_app.Currency')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
