# Generated by Django 2.2.10 on 2021-02-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio_tracker_app', '0002_stocks_date_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_name',
            field=models.CharField(max_length=200),
        ),
    ]
